name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          cache: true

      - name: Restore
        run: dotnet restore "habit-hub-server/HabitHub.sln"

      - name: Build
        run: dotnet build "habit-hub-server/HabitHub.sln" -c Release --no-restore
